name: Build my Application

on: [push]

jobs:
    build:
        name: Build our App
        runs-on: ubuntu-latest
        steps:
          - name: Pull Code
            uses: actions/checkout@v2
          - uses: actions/setup-dotnet@v1
            with:
              dotnet-version: '3.1.x'
          - name: Check Dotnet Cli
            run: dotnet --version
          - name: Restore Dependencies
            run: dotnet restore
          - name: Print Current Directory
            run: pwd
          - name: Create Production Build
            run: dotnet publish -c Release --no-restore
          - name: List Files in Directory
            run: ls -R TrickingLibrary/
