name: Build my Application

on: [push]

jobs:
    build:
        name: Build our App
        runs-on: ubuntu-latest
        steps:
          - name: Pull Code
            uses: actions/checkout@v2
          - uses: actions/setup-dotnet@v1
            with:
              dotnet-version: '5.0.x'
          - name: Check Dotnet Cli
            run: dotnet --version
          - name: Restore Dependencies
            run: dotnet restore
          - name: Print Current Directory
            run: pwd
          - name: Create Production Build
            run: dotnet publish -c Release --no-restore
          - name: List Files in Directory
            run: ls -R TrickingLibrary.Api/
          - name: Inject Secrets
            uses: microsoft/variable-substitution@v1
            with:
              files: './TrickingLibrary.Api/bin/Release/net5.0/publish/appsettings.Production.json'
            env:
              SendGridOptions.ApiKey: ${{ secrets.SEND_GRID_API_KEY }}
              SendGridOptions.From: ${{ secrets.SEND_GRID_FROM }}
          - name: Cat json 2
            run: cat ./TrickingLibrary.Api/bin/Release/net5.0/publish/appsettings.Production.json
